<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobTitlesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('job_titles')->insert([
            [
                'name' => 'Owner', 
                'short_code' => 'OWN',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null, 
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'name' => 'Chief Executive Officer', 
                'short_code' => 'CEO',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null, 
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'name' => 'Chief Operations Officer', 
                'short_code' => 'COO',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null, 
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'name' => 'Chief Financial Officer', 
                'short_code' => 'CFO',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null, 
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'name' => 'Chief Technology Officer', 
                'short_code' => 'CTO',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null, 
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'name' => 'Chief Marketing Officer', 
                'short_code' => 'CMO',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null, 
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'name' => 'Chief Information Officer', 
                'short_code' => 'CIO',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null, 
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'name' => 'Chief Compliance Officer', 
                'short_code' => 'CCO',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null, 
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'name' => 'Chief Risk Officer', 
                'short_code' => 'CRO',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null, 
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'name' => 'Chief Data Officer', 
                'short_code' => 'CDO',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null, 
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'name' => 'Chief Customer Officer', 
                'short_code' => 'CCO',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null, 
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'name' => 'Chief Strategy Officer', 
                'short_code' => 'CSO',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null, 
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'name' => 'Chief Engineering Officer', 
                'short_code' => 'CEO',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null, 
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'name' => 'Chief HR Officer', 
                'short_code' => 'CHRO',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null, 
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'name' => 'Software Developer',
                'short_code' => 'SOF',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Data Scientist',
                'short_code' => 'DAT',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Network Administrator',
                'short_code' => 'NET',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Web Developer',
                'short_code' => 'WEB',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Database Administrator',
                'short_code' => 'DBA',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Accountant',
                'short_code' => 'ACC',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Financial Analyst',
                'short_code' => 'FIN',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Auditor',
                'short_code' => 'AUD',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tax Advisor',
                'short_code' => 'TAX',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Risk Manager',
                'short_code' => 'RIS',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Controller',
                'short_code' => 'CON',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Budget Analyst',
                'short_code' => 'BUD',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Civil Engineer',
                'short_code' => 'CIV',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mechanical Engineer',
                'short_code' => 'MEC',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Electrical Engineer',
                'short_code' => 'ELE',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chemical Engineer',
                'short_code' => 'CHE',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Structural Engineer',
                'short_code' => 'STR',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Environmental Engineer',
                'short_code' => 'ENV',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Photographer',
                'short_code' => 'PHO',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Musician',
                'short_code' => 'MUS',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Writer',
                'short_code' => 'WRI',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Animator',
                'short_code' => 'ANI',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marketer',
                'short_code' => 'MAR',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Project Manager',
                'short_code' => 'PM',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sales Manager',
                'short_code' => 'SM',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sales Associate',
                'short_code' => 'SA',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Customer Service Representative',
                'short_code' => 'CSR',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Inventory Manager',
                'short_code' => 'IM',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Floor Supervisor',
                'short_code' => 'FS',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Team Manager',
                'short_code' => 'TM',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Human Resources Manager',
                'short_code' => 'HRM',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HR Generalist',
                'short_code' => 'HRG',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Recruitment Specialist',
                'short_code' => 'REC',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HR Coordinator',
                'short_code' => 'HRC',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Compensation and Benefits Specialist',
                'short_code' => 'CBS',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Training and Development Manager',
                'short_code' => 'TDM',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Employee Relations Specialist',
                'short_code' => 'ERS',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HR Analyst',
                'short_code' => 'HRAN',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HR Assistant',
                'short_code' => 'HRAS',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HR Director',
                'short_code' => 'HRD',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
